default: &default
  adapter: postgresql
  encoding: unicode
  host: <%= ENV['POSTGRES_HOST'] %>
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5

development:
  <<: *default
  database: rails_workshop_development

test:
  <<: *default
  database: rails_workshop_test

production:
  <<: *default
  database: <%= "#{ENV['DATABASE_NAME']}-production" || '' %>
  password: <%= ENV['TRAIN_IT_DATABASE_PASSWORD'] %>
